name: CI-CD_pipeline-to-AWS-ElasticBeansTalk
env:
  EB_PACKEGE_S3_BUCKET_NAME : "my-git-test-flask-packages"
  EB_APLICATION_NAME        : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKEGE_NAME       : "Flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"

on:
  push:
    branches: 
    - master
    
jobs:
  my_CI_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone oure repo
        uses: actions/checkout@v2

      - name: Create zip deployment package
        run : zip -r ${{ env.DEPLOY_PACKEGE_NAME }} ./ -x *.git*
        
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id      : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key  : ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region             : ${{ env.AWS_REGION_NAME }}
          
      - name: Copy Deployment pakage to AWS BacketS3
        run: aws s3 cp ${{ env.DEPLOY_PACKEGE_NAME }} s3://${{ env.EB_PACKEGE_S3_BUCKET_NAME }}/
        
      - name: Happy messege for CI Finish
        run: echo "CI Piplene part Finished"
